-- MySQL Script generated by MySQL Workbench
-- Fri Jan 19 13:37:58 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

CREATE DATABASE inventario DEFAULT CHARACTER SET utf8; 

USE inventario; 
-- -----------------------------------------------------
-- Table provedor
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS proveedor (
  rfc VARCHAR(13) NOT NULL,
  nombre_provedor VARCHAR(60) NOT NULL DEFAULT '',
  domicilio_fiscal VARCHAR(300) NOT NULL DEFAULT '',
  domicilio_particular VARCHAR(300) NULL,
  telefono VARCHAR(30) NOT NULL DEFAULT '',
  telefono2 VARCHAR(30) NULL,
  email VARCHAR(60) NOT NULL DEFAULT '',
  pag_web VARCHAR(60) NULL,
  tipo_persona TINYINT(1) NOT NULL DEFAULT 0,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (rfc))
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


-- -----------------------------------------------------
-- Table factura
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS factura (
  no_factura VARCHAR(40) NOT NULL,
  rfc VARCHAR(13) NOT NULL,
  no_resguardo VARCHAR(45) NULL COMMENT 'NUMERO INTERNO DE CONTI',
  fecha_emision DATETIME NOT NULL,
  anios_garantia TINYINT(2) NOT NULL DEFAULT 0,
  subtotal DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  iva DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  total DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (no_factura),
  INDEX fk_Factura_1_idx (rfc ASC),
  CONSTRAINT fk_Factura_1
    FOREIGN KEY (rfc)
    REFERENCES proveedor (rfc)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


-- -----------------------------------------------------
-- Table dgac.areas_dgac
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS dgac; 
CREATE TABLE IF NOT EXISTS dgac.areas_dgac (
  id_area_dgac TINYINT NOT NULL COMMENT '1 = EDUCACION\n2 = INVETIGACION\n3 = DIFUSION CULTURAL\n4 = ADMINISTRATIVO/SERVICIOS\n',
  nombre_area VARCHAR(50) NOT NULL,
  cd_ubicacion VARCHAR(13) NOT NULL,
  PRIMARY KEY (id_area_dgac))
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

INSERT INTO dgac.areas_dgac VALUES(0, 'Recepcion de Ingresos', 'LU100A01-01 4');
INSERT INTO dgac.areas_dgac VALUES(1, 'Taller de Rescate y Restauracion', 'LU101A01-01 2');
INSERT INTO dgac.areas_dgac VALUES(2, 'Videotaller', 'LU102A01-01 0');
INSERT INTO dgac.areas_dgac VALUES(3, 'Lab quimico', 'LU103A01-01 8');
INSERT INTO dgac.areas_dgac VALUES(4, 'Lab digital', 'LU104A01-01 6');
INSERT INTO dgac.areas_dgac VALUES(5, 'Bovedas', 'LU105A01-01 3');
INSERT INTO dgac.areas_dgac VALUES(6, 'Subdireccion de Rescate y Restauracion', 'LU106A01-01 1');
INSERT INTO dgac.areas_dgac VALUES(7, 'Subdireccion de Acervos', 'LU107A01-01 9');
INSERT INTO dgac.areas_dgac VALUES(8, 'Unidad de Acceso Interinstitucional', 'LU108A01-01 7');
INSERT INTO dgac.areas_dgac VALUES(9, 'Coordinacion de Nuevas Tecnologias e Informatica', 'LU109A01-01 5');
INSERT INTO dgac.areas_dgac VALUES(10, 'Centro de Documentacion', 'LU110A01-01 3');
INSERT INTO dgac.areas_dgac VALUES(11, 'Catalogacion', 'LU111A01-01 1');
INSERT INTO dgac.areas_dgac VALUES(12, 'Banco de Imagen', 'LU112A01-01 9');
INSERT INTO dgac.areas_dgac VALUES(13, 'Produccion', 'LU113A01-01 7');
INSERT INTO dgac.areas_dgac VALUES(14, 'Difusion', 'LU114A01-01 5');
INSERT INTO dgac.areas_dgac VALUES(15, 'Exhibicion', 'LU115A01-01 2');
INSERT INTO dgac.areas_dgac VALUES(16, 'ARPPFU', 'LU116A01-01 0');
INSERT INTO dgac.areas_dgac VALUES(17, 'Depositante', 'LU117A01-01 8');
INSERT INTO dgac.areas_dgac VALUES(18, 'Depositante Salida Definitiva', 'LU118A01-01 6');
INSERT INTO dgac.areas_dgac VALUES(19, 'Baja', 'LU119A01-01 4');


-- -----------------------------------------------------
-- Table usuario
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario (
  id_usuario TINYINT UNSIGNED NOT NULL,
  id_area_dgac TINYINT NOT NULL,
  no_empleado INT(8) NULL,
  tipo_usuario TINYINT(2) NOT NULL DEFAULT 0 COMMENT '1 = ALUMNOS\n2 = INVESTIGACION\n3 = PERSONAL ACADEMICO\n4 = PERSONAL ADMINISTRATIVO\n5 = BIBLIOTECA USUARIO\n6 = BIBLIOTECA ADMINISTRATIVO\n7 = SERVIDOR WEB\n8 = SERVIDOR',
  nombre_completo VARCHAR(40) NOT NULL,
  perfil_usuario TINYINT(2) NOT NULL DEFAULT 0 COMMENT '1 = ESTUDIANTE\n2 = ACADEMICO\n3 = INVESTIGADOR\n4 = FUNCIONARIO\n5 = ADMINISTRATIVO',
  activo TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (id_usuario),
  UNIQUE INDEX NoEmpleado_UNIQUE (no_empleado ASC),
  INDEX fk_usuario_areas_dgac1_idx (id_area_dgac ASC),
  CONSTRAINT fk_usuario_areas_dgac1
    FOREIGN KEY (id_area_dgac)
    REFERENCES dgac.areas_dgac (id_area_dgac)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


-- -----------------------------------------------------
-- Table equipo
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS equipo (
  no_inventario INT(8) NOT NULL,
  id_usuario TINYINT UNSIGNED NULL,
  id_responsable TINYINT UNSIGNED NOT NULL,
  no_factura VARCHAR(40) NULL,
  no_serie VARCHAR(30) NOT NULL,
  localizacion VARCHAR(45) NOT NULL,
  marca VARCHAR(15) NOT NULL,
  modelo VARCHAR(25) NOT NULL,
  tipo_equipo TINYINT(2) NOT NULL DEFAULT 0 COMMENT '1 = TABLETA\n2 = PORTATIL\n3 = PC DE ESCRITORIO\n4 = TODO EN UNO\n5 = ESTACION DE TRABAJO\n6 = SERVIDOR\n7 = CLUSTER\n8 = CLIENTE LIGERO',
  num_arreglos TINYINT(2) UNSIGNED NOT NULL DEFAULT 0,
  tec_comunicacion TINYINT(2) NOT NULL DEFAULT 0 COMMENT '1 = ETHERNET\n2 = WIFI\n3 = ETHERNET-WIFI\n4 = 3G/4G',
  tec_comunicacion_dif VARCHAR(15) NULL,
  os TINYINT(2) NOT NULL DEFAULT 0 COMMENT '1 = WINDOWS\n2 = LINUX\n3 = MAC OS\n4 = UNIX\n5 = SOLARIS\n6 = ANDROID\n7 = IOS\n8 = FREEBSB\n9 = WINDOWS MOBILE',
  os_version VARCHAR(15) NOT NULL DEFAULT '',
  os_edicion VARCHAR(15) NOT NULL DEFAULT '',
  os_arq TINYINT(2) NOT NULL DEFAULT 0,
  os_release VARCHAR(20) NOT NULL DEFAULT '',
  num_procesadores TINYINT(2) NOT NULL,
  num_ram_instaladas TINYINT(2) NOT NULL,
  tipo_licencia VARCHAR(15) NOT NULL DEFAULT '',
  licencia_inicio DATE NOT NULL,
  licencia_fin DATE NOT NULL,
  unidad_optica VARCHAR(20) NOT NULL DEFAULT '',
  ip4 VARCHAR(20) NOT NULL DEFAULT '',
  ip6 VARCHAR(40) NOT NULL DEFAULT '',
  observaciones VARCHAR(200) NOT NULL DEFAULT '',
  know_how JSON DEFAULT NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (no_inventario),
  INDEX fk_Equipo_4_idx (no_factura ASC),
  UNIQUE INDEX NoInventario_UNIQUE (no_inventario ASC),
  INDEX fk_Equipo_5_idx (id_usuario ASC),
  INDEX fk_equipo_usuario1_idx (id_responsable ASC),
  CONSTRAINT fk_Equipo_4
    FOREIGN KEY (no_factura)
    REFERENCES factura (no_factura)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_Equipo_5
    FOREIGN KEY (id_usuario)
    REFERENCES usuario (id_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_equipo_usuario1
    FOREIGN KEY (id_responsable)
    REFERENCES usuario (id_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


-- -----------------------------------------------------
-- Table cat_tipos_eq_perif
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS cat_tipos_eq_perif (
  id_tipos_eq_perif SMALLINT(4) NOT NULL AUTO_INCREMENT,
  nombre_tipo_eq_perif VARCHAR(100) NOT NULL,
  PRIMARY KEY (id_tipos_eq_perif))
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


-- -----------------------------------------------------
-- Table periferico
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS periferico (
  no_factura VARCHAR(40) NOT NULL,
  num_serie VARCHAR(45) NOT NULL,
  id_tipos_eq_perifs SMALLINT(4) NOT NULL,
  id_usuario TINYINT UNSIGNED NULL,
  id_responsable TINYINT UNSIGNED NOT NULL,
  no_inventario INT(8) NOT NULL,
  marca VARCHAR(45) NOT NULL,
  modelo VARCHAR(45) NOT NULL,
  localizacion VARCHAR(45) NOT NULL,
  interfaz VARCHAR(15) NULL,
  nucleos SMALLINT(4) NULL,
  memoria VARCHAR(20) NULL,
  velocidad VARCHAR(20) NULL,
  cantidad SMALLINT(4) NOT NULL DEFAULT 0,
  ip4 VARCHAR(20) NULL,
  ip6 VARCHAR(40) NULL,
  observaciones VARCHAR(200) NOT NULL,
  know_how JSON DEFAULT NULL,
  activo TINYINT(1) NOT NULL DEFAULT 1,
  INDEX fk_Periferico_2_idx (no_factura ASC),
  INDEX fk_periferico_usuario1_idx (id_usuario ASC),
  INDEX fk_periferico_usuario2_idx (id_responsable ASC),
  INDEX fk_periferico_otros_cat_tipos_eq_perifs1_idx (id_tipos_eq_perifs ASC),
  PRIMARY KEY (no_factura, num_serie),
  CONSTRAINT fk_Periferico_2
    FOREIGN KEY (no_factura)
    REFERENCES factura (no_factura)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_periferico_usuario1
    FOREIGN KEY (id_usuario)
    REFERENCES usuario (id_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_periferico_usuario2
    FOREIGN KEY (id_responsable)
    REFERENCES usuario (id_usuario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_periferico_otros_cat_tipos_eq_perifs1
    FOREIGN KEY (id_tipos_eq_perifs)
    REFERENCES cat_tipos_eq_perif (id_tipos_eq_perif)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET utf8
COMMENT = '	';


-- -----------------------------------------------------
-- Table cat_catic_ram
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS cat_catic_ram (
  id_catic_ram TINYINT UNSIGNED NOT NULL COMMENT 'CATIC 2017\n1 = DDR1\n2 = DDR2\n3 = DDR3\n4 = DDR4\n5 = EPROM',
  nombre_ram VARCHAR(10) NOT NULL,
  PRIMARY KEY (id_catic_ram))
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

INSERT INTO `inventario`.`cat_catic_ram` (`id_catic_ram`, `nombre_ram`) VALUES ('1', 'DDR1');
INSERT INTO `inventario`.`cat_catic_ram` (`id_catic_ram`, `nombre_ram`) VALUES ('2', 'DDR2');
INSERT INTO `inventario`.`cat_catic_ram` (`id_catic_ram`, `nombre_ram`) VALUES ('3', 'DDR3');
INSERT INTO `inventario`.`cat_catic_ram` (`id_catic_ram`, `nombre_ram`) VALUES ('4', 'DDR4');
INSERT INTO `inventario`.`cat_catic_ram` (`id_catic_ram`, `nombre_ram`) VALUES ('5', 'EPROM5');



-- -----------------------------------------------------
-- Table ram
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS ram (
  id_ram INT UNSIGNED NOT NULL,
  tipo_ram TINYINT UNSIGNED NOT NULL,
  tipo_ram_diferente VARCHAR(15) NULL DEFAULT '',
  capacidad DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  escala_capacidad VARCHAR(2) NOT NULL DEFAULT '',
  velocidad SMALLINT NOT NULL DEFAULT 0,
  escala_velocidad VARCHAR(3) NOT NULL DEFAULT '',
  PRIMARY KEY (id_ram),
  INDEX fk_ram_cat_ram1_idx (tipo_ram ASC),
  CONSTRAINT fk_ram_cat_ram1
    FOREIGN KEY (tipo_ram)
    REFERENCES cat_catic_ram (id_catic_ram)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


-- -----------------------------------------------------
-- Table cat_catic_procesador
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS cat_catic_procesador (
  id_catic_procesador TINYINT UNSIGNED NOT NULL COMMENT 'CATIC 2017\n1 = INTEL 386\n2 = INTEL 486\n3 = INTEL PENTIUM\n4 = INTEL CELERON\n5 = INTEL CORE DUO\n6 = INTEL ATOM\n7 = INTEL I3\n8 = INTEL I5\n9 = INTEL I7\n10 = INTEL XEON\n11 = INTEL DURON\n12 = AMD SEMPRON\n13 = AMD TURION\n14 = AMD PHEMON\n15 = AMD A3\n15 = AMD A6\n17 = AMD A8\n18 = AMD A10\n19 = ARM\n20 = QUALCOMM\n21 = MKT\n22 = OTRO',
  nombre_procesador VARCHAR(20) NOT NULL,
  PRIMARY KEY (id_catic_procesador))
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;

INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('1', 'INTEL 386');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('2', 'INTEL 486');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('3', 'INTEL PENTIUM');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('4', 'INTEL CELERON');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('5', 'INTEL CORE DUO');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('6', 'INTEL ATOM');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('7', 'INTEL I3');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('8', 'INTEL I5');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('9', 'INTEL I7');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('10', 'INTEL XEON');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('11', 'INTEL DURON');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('12', 'AMD SEMPRON');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('13', 'AMD TURION ');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('14', 'AMD PHENOM');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('15', 'AMD A3');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('16', 'AMD A6');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('17', 'AMD A8');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('18', 'AMD A10');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('19', 'ARM');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('20', 'QUALCOMM');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('21', 'MKT');
INSERT INTO `inventario`.`cat_catic_procesador` (`id_catic_procesador`, `nombre_procesador`) VALUES ('22', 'OTRO');


-- -----------------------------------------------------
-- Table procesador
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS procesador (
  id_procesador INT UNSIGNED NOT NULL,
  tipo_procesador TINYINT UNSIGNED NOT NULL,
  tipo_procesador_diferente VARCHAR(20) NULL,
  modelo_procesador VARCHAR(20) NOT NULL DEFAULT '',
  cant_nucleos SMALLINT(4) NOT NULL DEFAULT 0,
  cant_nucleos_gpu SMALLINT(4) NOT NULL DEFAULT 0,
  velocidad DECIMAL(6,2) NOT NULL DEFAULT 0.0,
  escala_velocidad VARCHAR(3) NOT NULL DEFAULT '',
  marca VARCHAR(20) NOT NULL DEFAULT '',
  arquitectura TINYINT(2) NOT NULL DEFAULT 0,
  PRIMARY KEY (id_procesador),
  INDEX fk_procesador_cat_procesador1_idx (tipo_procesador ASC),
  CONSTRAINT fk_procesador_cat_procesador1
    FOREIGN KEY (tipo_procesador)
    REFERENCES cat_catic_procesador (id_catic_procesador)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


-- -----------------------------------------------------
-- Table disco_duro
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS disco_duro (
  id_disco_duro INT UNSIGNED NOT NULL,
  no_inventario INT(8) NOT NULL,
  tecnologia_dd TINYINT(2) NOT NULL DEFAULT 0 COMMENT '1 = SATA I\n2 = SATA II\n3 = SATA III\n4 = IDE\n5 = SCSI\n6 = FLASH\n7 = SSD',
  capacidad_total DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  escala_capacidad VARCHAR(2) NOT NULL DEFAULT '',
  tipo_dd VARCHAR(10) NOT NULL DEFAULT '',
  PRIMARY KEY (id_disco_duro),
  INDEX fk_DiscoDuro_1_idx (no_inventario ASC),
  CONSTRAINT fk_DiscoDuro_1
    FOREIGN KEY (no_inventario)
    REFERENCES equipo (no_inventario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


-- -----------------------------------------------------
-- Table arreglos
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS arreglos (
  no_inventario INT(8) NOT NULL,
  num_arreglo TINYINT(2) NOT NULL,
  esquema VARCHAR(10) NOT NULL DEFAULT '',
  tecnologia_dd VARCHAR(15) NOT NULL DEFAULT '',
  capacidad_arr DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  escala_capacidad VARCHAR(2) NOT NULL DEFAULT '',
  PRIMARY KEY (no_inventario, num_arreglo),
  INDEX fk_Arreglos_1_idx (no_inventario ASC),
  CONSTRAINT fk_Arreglos_1
    FOREIGN KEY (no_inventario)
    REFERENCES equipo (no_inventario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


-- -----------------------------------------------------
-- Table trans_ram_equipo
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS trans_ram_equipo (
  id_ram INT UNSIGNED NOT NULL,
  no_inventario INT(8) NOT NULL,
  PRIMARY KEY (id_ram, no_inventario),
  INDEX fk_ram_has_equipo_equipo1_idx (no_inventario ASC),
  INDEX fk_ram_has_equipo_ram1_idx (id_ram ASC),
  CONSTRAINT fk_ram_has_equipo_ram1
    FOREIGN KEY (id_ram)
    REFERENCES ram (id_ram)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_ram_has_equipo_equipo1
    FOREIGN KEY (no_inventario)
    REFERENCES equipo (no_inventario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;


-- -----------------------------------------------------
-- Table trans_procesador_equipo
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS trans_procesador_equipo (
  id_procesador INT UNSIGNED NOT NULL,
  no_inventario INT(8) NOT NULL,
  PRIMARY KEY (id_procesador, no_inventario),
  INDEX fk_procesador_has_equipo_equipo1_idx (no_inventario ASC),
  INDEX fk_procesador_has_equipo_procesador1_idx (id_procesador ASC),
  CONSTRAINT fk_procesador_has_equipo_procesador1
    FOREIGN KEY (id_procesador)
    REFERENCES procesador (id_procesador)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_procesador_has_equipo_equipo1
    FOREIGN KEY (no_inventario)
    REFERENCES equipo (no_inventario)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB DEFAULT CHARACTER SET utf8;